name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout full repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important: get full history for --mirror to work

    - name: Mirror to Azure DevOps
      env:
        AZURE_REPO_URL: https://jeremydumais.visualstudio.com/The%20Warrior/_git/The%20Warrior
        AZURE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        git config --global user.email "jeremydumais@hotmail.com"
        git config --global user.name "Jeremy Dumais"

        git remote add azure https://jeremydumais:${AZURE_PAT}@jeremydumais.visualstudio.com/The%20Warrior/_git/The%20Warrior
        git push --mirror azure
